### ISSUE TITLE
missing fonts

### ISSUE THREAD

**Issue by SecretSquirrel77** [AmazingVanish/apsj#1]
On initial load, scalysans.otf and scalysanscaps.otf are error404 not found.

**Comment by AmazingVanish** [comment]
Hmm. I'll dig around and see what would be causing that. Thanks for the report!

**Comment by AmazingVanish** [comment]
I made a change to how the ScalySans fonts were being referenced and it appears to have fixed the issue for me as of version 0.9.6. I'd love it if you could let me know if it's fixed for you as well. Thanks!

**Comment by SecretSquirrel77** [comment]
Love your work here! With the latest update, I'm now seeing BookInsanity.otf showing error404 aborted. Additionally there seems to be some errors with the CSS which results in the journal interface remaining open even when the journal itself is saved/closed.
![journal test](https://user-images.githubusercontent.c
![journal test 2](https://user-images.githubusercontent.com/77705375/152707121-d81b97c2-857f-4228-94b5-95625e5ba12c.PNG)
om/77705375/152707112-3b120f48-47c7-48d4-87fb-5ef6040dfd2c.PNG)

**Comment by SecretSquirrel77** [comment]
Updated to 1.2.1. BookInsanity still throwing 404 error, which seems to be preventing the opening of a couple of the templates. Also, the Settings panel will remain open when the journal is closes unless manually closed by the user. Good luck, it's super cool!

**Comment by AmazingVanish** [comment]
I cannot reproduce the things you're seeing. I suspect you have another mod conflicting with it. COuld you try just enabling apsj and see if it still has the problem? Or better yet, install Find the Culprit and have it divide and conquer to figure out what is causing the problem.

**Comment by SecretSquirrel77** [comment]
will do

**Comment by AmazingVanish** [comment]
This issue moved to apsj4mej project.
