### ISSUE TITLE
[Suggestion] Add some key details to description

### ISSUE THREAD

**Issue by UnoriginalDM** [AmazingVanish/apsj#2]
Hello and thank you for the mod. This mod is an excellent replacement for the very outdated TinyMCE toolbar config mod and is not compatible with it. I did not realize until I really compared the two that your mod does everything TinyMCE toolbar did and more. 

I would recommend adding to the description of your mod that it also adds to the MCE and note the features of changing the font family, font color, text highlight color, and font size.

**Comment by AmazingVanish** [comment]
Thank you for the notification. I have added that it changes the toolbar with a screenshot of what it adds. I didn't even know that the other module even existed. I'll add more clarification and a conflict entry if it continues to be problematic. Great suggestion!
