### ISSUE TITLE
[Feature Request / BUG?] Character Sheet Background Changing

### ISSUE THREAD

**Issue by Mist-Hunter** [AmazingVanish/apsj#4]
Thank you for your beautiful journal add-on. I try and keep all my DM notes in foundry to keep tabbing out to a minimum and this makes things so much prettier AND easier to indicate to myself the things I need to convey.

I have noticed, however, that the wonderful parchment background you use is also applying to my character sheet backgrounds. I'm still digesting if I think this looks better, which I'm leaning towards yes :), but I didn't know this was going to happen when I installed this module. 

My suggestion is to create a setting to optionally disable this for character sheets, even though I think I might stick with it. Thanks again!

![image](https://user-images.githubusercontent.com/6420684/152689553-48f00b98-c7e4-4862-8b1b-82c31512cd7f.png)

![image](https://user-images.githubusercontent.com/6420684/152689578-4fee32fa-1c0f-4c7e-94ef-5f072233ef6e.png)

**Comment by AmazingVanish** [comment]
Oh. Well, then. I didn't know it was going to do that either. I've tried very hard not to interfere with other parts of the app. I'll dig around and see what I can do. Thanks for the head up!

**Comment by AmazingVanish** [comment]
Hmm, unfortunately, the character sheet and the journal use the exact same selector. THere's no way to differentiate them that I can find. (Not consistently) I'll keep digging but this may just end up a known issue. I'll have to see about creating an options panel to choose to enable or disable it.

**Comment by Mist-Hunter** [comment]
Thanks for the update and the module :) Do you want me to close this?

**Comment by AmazingVanish** [comment]
No, let's leave it open for now to see if I can find a way to handle it. :)

**Comment by AmazingVanish** [comment]
Aha! I found it. The next release won't impact character sheets. Thanks for letting me know about this!
![FoundIt!](https://user-images.githubusercontent.com/192720/152694781-4a260327-c566-4bb7-bfc0-a9cc61a9d2b9.png)

**Comment by Mist-Hunter** [comment]
No worries. Thanks for the awesome module! I love the polish it adds to my efforts
