### ISSUE TITLE
Menu problems

### ISSUE THREAD

**Issue by HippyCraig** [AmazingVanish/apsj#5]
Im using the latest foundry, Version 9 - Build 249.  When using the ... menu option to see more controls when I click the stamp too the menu doesnt clear out and just stays hovering where it first spawned.  Also the Styles menu, all those I cant click on, they just turn my mouse pointer into a red circle with a slask and I nothing changes on the entry.

**Comment by AmazingVanish** [comment]
Hi HippyCraig! It sounds like you need to update the mod. You shouldn't see the  '...' menu anymore. I made changes to prevent it specifically to address the persistent buttons showing even after you close the window.

As for the Styles menu, they only enable when you have text selected and they are of the correct type, like H1, H2, H3, etc. I'm playing around with that now to see if I can get them to enable always.

**Comment by HippyCraig** [comment]
So I am only testing the Regualar Stylish Journal in this case and only that one is enabled.  I was testing with 1.2.1, it was a fresh install from the install modual in Foundry.  I did run the update and it asked me to update the modual URL but it failed see attached.

![image](https://user-images.githubusercontent.com/17074456/153520241-497a1bef-c019-4e9c-b83e-e9d04420e59e.png)

**Comment by AmazingVanish** [comment]
Oh wow. Let me look into what may have happened.

**Comment by HippyCraig** [comment]
cool there both at 1.3.1 now, I can test the features tomorrow playing shadow run :)

Thanks!

**Comment by AmazingVanish** [comment]
Cool. Let me know!

**Comment by HippyCraig** [comment]
Thanks for the quick response, I was just testing it, no inconvience.
