### ISSUE TITLE
Issue with permissions when showing journals to players.

### ISSUE THREAD

**Issue by nulmas** [AmazingVanish/apsj#6]
This is a minor thing: when a GM shows a player a journal that the player has Owner-level permission to, the journal will display as intended.

However, if the permission is anything less than Owner, the journal will always show up with the default background:
![image](https://user-images.githubusercontent.com/79886727/154110211-5fe7b2c6-ab9b-44bf-bcde-730cc0fcc008.png)

The other features from Stylish Journal seem to still work ok, though.

**Comment by AmazingVanish** [comment]
Well that's interesting. I'll have to investigate why that is. Not sure I can do anything about it, but we'll see.

**Comment by AmazingVanish** [comment]
Fixed in v1.6.1 rolling out soon.

**Comment by fel-pt** [comment]
> Fixed in v1.6.1 rolling out soon.

Thank you (both for the fix and the great work with this module ;) )
