### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by HippyCraig** [AmazingVanish/apsj#9]
Will this be updated to work with v10?

**Comment by AmazingVanish** [comment]
@HippyCraig Well, yes and no. I am working on a v10 version, however it will likely require Monk's Enhanced Journal to function. More to come as I fiddle my way through the new journaling system.

**Comment by HippyCraig** [comment]
Thats great I already use M EJ.  Does that mean that it will only work with his templates?  Or will the base new Journal Books be supported as well?

What you have here is so much better than the one indented quote that is provided out of the box with Foundry.  If you need a tester let me know

**Comment by AmazingVanish** [comment]
if you're feeling adventurous and go into it knowing it's not complete, you can install the v10 project I'm working on from here: https://github.com/VanishsVault/apsjournal

**Comment by HippyCraig** [comment]
Thanks I will give it a go, I have a test world I can play with.  one I have been using for testing out other mods for v10
I assume any issue you wnat them logged under that apps issue log.
